name: ie-bank-infra

on:
  workflow_dispatch: #Allows you to manually trigger the workflow from the GitHub Actions tab.
  pull_request:
      branches:
        - main
  push:
      branches:
        - '*'
      paths-ignore:
        - 'scripts/'

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: sofias

jobs:
  build:
    runs-on: ubuntu-latest
    steps:


  deploy-dev:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:

      # Checkout code
    - uses: actions/checkout@main

    - name: Download Bicep build artifact
      uses: actions/download-artifact@v4
      with:
          name: bicep-build

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: Deploy to dev
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{env.SUBSCRIPTION_ID_DEV }}
        resourceGroupName: ${{env.RESOURCE_GROUP_DEV }}
        template: ./infraestructure/main.bicep
        parameters: ./infraestructure/parameters/dev.parameters.json